# Generated by Django 6.0.4 on 2026-04-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='categories/', blank=True, null=True)
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='products/', blank=True, null=True)
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
