# Generated by Django 6.0.4 on 2026-04-29 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0002_remove_category_image_url_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='cashier',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmep.poitem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmep.saleitem'),
        ),
    ]
