# Generated by Django 6.0.4 on 2026-04-30 03:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0004_remove_category_img_remove_stockmovement_cashier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cashier',
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Cashier',
        ),
    ]
