# Generated by Django 6.0.4 on 2026-04-16 01:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
