# Generated by Django 6.0.4 on 2026-04-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0006_sale_order_code_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='products/'),
        ),
    ]
