# Generated by Django 6.0.4 on 2026-05-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0007_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='line_total',
            field=models.FloatField(default=0),
        ),
    ]
