# Generated by Django 6.0.4 on 2026-04-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0007_alter_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_best',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COD', 'Cash on Delivery'), ('GCASH', 'GCash')], max_length=50, null=True),
        ),
    ]
