# Generated by Django 6.0.4 on 2026-04-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0008_remove_product_is_best_remove_product_is_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='support@dmep.com', max_length=254)),
                ('phone', models.CharField(default='+63 9XX XXX XXXX', max_length=50)),
                ('response_time', models.CharField(default='24–48 hours', max_length=100)),
                ('shipping_processing', models.CharField(default='1–2 business days', max_length=100)),
                ('shipping_metro', models.CharField(default='2–5 days', max_length=100)),
                ('shipping_provincial', models.CharField(default='3–10 days', max_length=100)),
                ('returns_days', models.IntegerField(default=7)),
                ('refund_time', models.CharField(default='3–5 business days', max_length=100)),
                ('shipping_refundable', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
