# Generated by Django 6.0.4 on 2026-05-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0008_poitem_line_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poitem',
            old_name='line_total',
            new_name='line_total2',
        ),
    ]
