# Generated by Django 6.0.4 on 2026-05-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0009_rename_line_total_poitem_line_total2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poitem',
            name='line_total2',
        ),
    ]
