# Generated by Django 6.0.4 on 2026-05-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0010_remove_poitem_line_total2'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='line_total',
            field=models.FloatField(default=0),
        ),
    ]
