# Generated by Django 6.0.4 on 2026-04-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0011_alter_sale_status_ordertracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('refunded', 'Refunded'), ('shipped', 'Shipped'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=50, null=True),
        ),
    ]
