# Generated by Django 6.0.4 on 2026-05-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0011_poitem_line_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poitem',
            name='line_total',
        ),
    ]
