# Generated by Django 6.0.4 on 2026-04-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0013_alter_cashier_role_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='guest_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
