# Generated by Django 6.0.4 on 2026-04-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0015_discount_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='discount_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
