# Generated by Django 6.0.4 on 2026-04-25 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0016_saleitem_discount_name_saleitem_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 25, 5, 19, 4, 231726, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
