# Generated by Django 6.0.4 on 2026-04-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0017_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
    ]
